<?php

namespace CollectionBundle\Repository;

/**
 * GarageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEnableGarageQb()
    {
        return $this->createQueryBuilder('g')
            ->leftJoin('g.car', "c")
            ->groupBy("g")
            ->having('count(c) <> g.capacity');
    }
}